FileListElement.o: FileListElement.cc FileListElement.h FileType.h \
 PathResolver.h
FilePanelFooter.o: FilePanelFooter.cc FilePanelFooter.h
FilesColumns.o: FilesColumns.cc FilesColumns.h
FilesNavigationPanel.o: FilesNavigationPanel.cc FilesNavigationPanel.h \
 Settings.h Rectangle.h SinglePanel.h FileListElement.h FileType.h \
 PanelHeader.h PathResolver.h FilesTreeView.h SelectionHistory.h \
 GuiReader.h ThreadMessage.h FilePanelFooter.h
FilesTreeView.o: FilesTreeView.cc FilesTreeView.h FilesColumns.h config.h
GuiReader.o: GuiReader.cc GuiReader.h ThreadMessage.h FileListElement.h \
 FileType.h PathResolver.h ThreadCalculation.h config.h
MainWindow.o: MainWindow.cc MainWindow.h Rectangle.h \
 FilesNavigationPanel.h Settings.h SinglePanel.h FileListElement.h \
 FileType.h PanelHeader.h PathResolver.h FilesTreeView.h \
 SelectionHistory.h GuiReader.h ThreadMessage.h FilePanelFooter.h \
 config.h MenuBar.h
MenuBar.o: MenuBar.cc MenuBar.h SettingsWindow.h config.h
PanelHeader.o: PanelHeader.cc PanelHeader.h
PathResolver.o: PathResolver.cc PathResolver.h
Preconditions.o: Preconditions.cc Preconditions.h
Rectangle.o: Rectangle.cc Rectangle.h
SelectionHistory.o: SelectionHistory.cc SelectionHistory.h PathResolver.h \
 config.h
Settings.o: Settings.cc Settings.h Rectangle.h config.h
SettingsWindow.o: SettingsWindow.cc SettingsWindow.h SizeDisplayFormat.h \
 config.h Settings.h Rectangle.h
SinglePanel.o: SinglePanel.cc SinglePanel.h FileListElement.h FileType.h \
 PanelHeader.h PathResolver.h FilesTreeView.h SelectionHistory.h \
 GuiReader.h ThreadMessage.h FilePanelFooter.h FilesColumns.h config.h \
 Preconditions.h
SizeDisplayFormat.o: SizeDisplayFormat.cc SizeDisplayFormat.h
SizeFormatterFactory.o: SizeFormatterFactory.cc SizeFormatterFactory.h \
 SizeFormatter.h SizeDisplayFormat.h SizeFormatterHr.h Settings.h \
 Rectangle.h SizeFormatterSimple.h SizeFormatterSpaces.h
SizeFormatterHr.o: SizeFormatterHr.cc SizeFormatterHr.h SizeFormatter.h \
 SizeDisplayFormat.h
SizeFormatterSimple.o: SizeFormatterSimple.cc SizeFormatterSimple.h \
 SizeFormatter.h SizeDisplayFormat.h
SizeFormatterSpaces.o: SizeFormatterSpaces.cc SizeFormatterSpaces.h \
 SizeFormatter.h SizeDisplayFormat.h
ThreadCalculation.o: ThreadCalculation.cc ThreadCalculation.h \
 ThreadMessage.h FileListElement.h FileType.h PathResolver.h config.h \
 SizeFormatterFactory.h SizeFormatter.h SizeDisplayFormat.h
ThreadMessage.o: ThreadMessage.cc ThreadMessage.h FileListElement.h \
 FileType.h PathResolver.h config.h
debug.o: debug.cc debug.h
main.o: main.cc config.h MainWindow.h Rectangle.h FilesNavigationPanel.h \
 Settings.h SinglePanel.h FileListElement.h FileType.h PanelHeader.h \
 PathResolver.h FilesTreeView.h SelectionHistory.h GuiReader.h \
 ThreadMessage.h FilePanelFooter.h
