#ifndef FILE_FLEET_ADMIRAL_FILEICONSRENDERINGTYPE_H
#define FILE_FLEET_ADMIRAL_FILEICONSRENDERINGTYPE_H
enum FileIconsRenderingType {
    ALWAYS_SAME_ICON,
    FILE_AND_DIR_DISTINCT_ICON,
    FILE_TYPE_PER_ICON
};
#endif //FILE_FLEET_ADMIRAL_FILEICONSRENDERINGTYPE_H
